variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - setup
  - test
  - build
  - integration-test
  - deploy
  - badges

include:
  - local: '.gitlab/ci-templates/Python-Service.gitlab-ci.yml'
  - local: '.gitlab/ci-templates/Kubernetes-Deploy.gitlab-ci.yml'
  - local: 'services/arango-candles/.gitlab-ci.yml'
  - local: 'services/arango-connector/.gitlab-ci.yml'
  - local: 'services/arango-graph-prep/.gitlab-ci.yml'
  - local: 'services/arango-orderbook/.gitlab-ci.yml'
  - local: 'services/arango-trades/.gitlab-ci.yml'
  - local: 'services/indicator-calculator/.gitlab-ci.yml'
  - local: 'services/dummy-service/.gitlab-ci.yml'
  - local: 'services/gnn-trainer/.gitlab-ci.yml'
  - local: 'services/graph_build/.gitlab-ci.yml'
  - local: 'services/loader-api-candles/.gitlab-ci.yml'
  - local: 'services/loader-api-trades/.gitlab-ci.yml'
  - local: 'services/loader-producer/.gitlab-ci.yml'
  - local: 'services/loader-ws-candles/.gitlab-ci.yml'
  - local: 'services/loader-ws-orderbook/.gitlab-ci.yml'
  - local: 'services/loader-ws-trades/.gitlab-ci.yml'
  - local: 'services/queue-manager/.gitlab-ci.yml'
  - local: 'services/visualizer/.gitlab-ci.yml'
  - local: 'platform/.gitlab-ci.yml'
