FROM registry.dmz.home/kinga/stream-forge/base:v0.1.3

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app ./app

# Default command to run the application
CMD ["python", "-m", "app.main"]
