include:
  - project: 'kinga/stream-forge'
    ref: main
    file: '/.gitlab/ci-templates/Python-Service.gitlab-ci.yml'
  - project: 'kinga/stream-forge'
    ref: main
    file: '/.gitlab/ci-templates/Kubernetes-Deploy.gitlab-ci.yml'

test-arango-connector:
  extends: .test_python_service
  variables:
    SERVICE_PATH: services/arango-connector
  when: manual

build-arango-connector:
  extends: .build_python_service
  needs:
    - test-arango-connector
  variables:
    SERVICE_NAME: arango-connector
    SERVICE_PATH: services/arango-connector
    CI_REGISTRY_IMAGE: $CI_REGISTRY/kinga/stream-forge/arango-connector

integration-test-arango-connector:
  extends: .integration_test_python_service
  needs:
    - build-arango-connector
  variables:
    SERVICE_NAME: arango-connector
    SERVICE_PATH: services/arango-connector
    ARANGO_URL: http://abase-3.dmz.home:8529
  before_script:
    # Ensure curl is available for health checks and install dependencies
    - apt-get update && apt-get install -y curl
    - pip install -r $CI_PROJECT_DIR/$SERVICE_PATH/requirements.txt
    - pip install -r $CI_PROJECT_DIR/$SERVICE_PATH/requirements-test.txt
    - echo "--- INSTALLED PACKAGES ---" && pip list && echo "------------------------"
    # Start the service in the background from the correct directory
    - (cd $CI_PROJECT_DIR/$SERVICE_PATH && python -m app.main --noop &)
    - echo "NOOP mode, skipping health check."



deploy-arango-connector:
  extends: .deploy_kubernetes_service
  needs:
    - integration-test-arango-connector
  variables:
    K8S_MANIFEST_PATH: services/arango-connector/k8s/arango-connector-job.yaml

update-badge-arango-connector:
  extends: .update_badge_python_service
  needs:
    - build-arango-connector
    - deploy-arango-connector
  variables:
    SERVICE_NAME: arango-connector
    SERVICE_PATH: services/arango-connector
  when: manual # Make it manual for now, user can change later
